name: "Prepare environment."
desccription: "Prepare .NET Core project."

inputs:
  skd-version:
    description: "Version of .NET Core SDK."
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
        run: dotnet restore
        with:
          dotnet-version: ${{ inputs.skd-version }}