name: Build and Test

on:
  push:
    branches: [ '*' ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}
#      - uses: actions/upload-artifact@v2
#        with:
#          name: build-artifact
#          path: 'src/'

  integration_test:

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Folders
        run: ls
      - name: Test
        run: dotnet test --no-build --verbosity normal

  unit_test:

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Folders
        run: ls
      - name: Test
        run: dotnet test --no-build --verbosity normal