name: Deploy DEV

on:
  # Automatic trigger when pushing tags
  # push:
  #   branches:
  #     - "!*"
  #   tags:
  #     - 'v*'

  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        required: false
        description: 'Build description'

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - complete

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Folders
        run: ls
