name: Deploy DEV

on:
  workflow_run:
    workflows: [ "Build and Test" ]
    branches: [ '*' ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v2
      - name: Folders
        run: ls