name: .NET

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/prepare-environment
        with:
          skd-version: 5.0.x
      - name: Build
        id: Build
        run: dotnet build --no-restore -c Release

  test:

    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: dotnet test --no-build --verbosity normal


