name: .NET

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: init-environment@v1
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        id: Build
        run: dotnet build --no-restore -c Release

  test:

    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: dotnet test --no-build --verbosity normal


