name: .NET

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Restore dependencies
        run: dotnet restore
        with:
          dotnet-version: ${{ inputs.skd-version }}
      - name: Build
        id: Build
        run: dotnet build --no-restore -c Release

  test:

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: dotnet test --no-build --verbosity normal